"""Initial migration with user, task_manager, and task_logger tables

Revision ID: 55839d7a9d6f
Revises: 
Create Date: 2025-04-05 01:41:01.472197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55839d7a9d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_manager_status'), ['status'], unique=False)
        batch_op.create_index('ix_task_status', ['status'], unique=False)

    op.create_table('task_logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_logger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_logger_changed_at'), ['changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_logger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_logger_changed_at'))

    op.drop_table('task_logger')
    with op.batch_alter_table('task_manager', schema=None) as batch_op:
        batch_op.drop_index('ix_task_status')
        batch_op.drop_index(batch_op.f('ix_task_manager_status'))

    op.drop_table('task_manager')
    op.drop_table('users')
    # ### end Alembic commands ###
